version: '3'
services:
  database:
    container_name: scout_db
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=scout123
      - POSTGRES_DB=scout
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5000:5432

volumes:
  postgres-data:
    driver: local